name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  base-alpine:
    name: Build and deploy the base Alpine image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to quay.io
        run: echo ${QUAY_PASSWORD} | docker login --username ${QUAY_USERNAME} --password-stdin quay.io
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

      - name: Build the image
        run: cd base-alpine && docker build --build-arg PULUMI_VERSION=${RELEASE_VERSION} --tag quay.io/spacelift/pulumi-base-alpine:${RELEASE_VERSION} .

      - name: Push the image to quay.io
        run: docker push quay.io/spacelift/pulumi-base-alpine:${RELEASE_VERSION}

  base-debian:
    name: Build and deploy the base Debian image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to quay.io
        run: echo ${QUAY_PASSWORD} | docker login --username ${QUAY_USERNAME} --password-stdin quay.io
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

      - name: Build the image
        run: cd base-debian && docker build --build-arg PULUMI_VERSION=${RELEASE_VERSION} --tag quay.io/spacelift/pulumi-base-debian:${RELEASE_VERSION} .

      - name: Push the image to quay.io
        run: docker push quay.io/spacelift/pulumi-base-debian:${RELEASE_VERSION}

  javascript:
    needs:
      - base-alpine
    name: Build and deploy the JavaScript image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to quay.io
        run: echo ${QUAY_PASSWORD} | docker login --username ${QUAY_USERNAME} --password-stdin quay.io
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

      - name: Build the image
        run: cd javascript && docker build --build-arg PULUMI_VERSION=${RELEASE_VERSION} --tag quay.io/spacelift/pulumi-javascript:${RELEASE_VERSION} .

      - name: Push the image to quay.io
        run: docker push quay.io/spacelift/pulumi-javascript:${RELEASE_VERSION}

  golang:
    needs:
      - base-alpine
    name: Build and deploy the Go image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to quay.io
        run: echo ${QUAY_PASSWORD} | docker login --username ${QUAY_USERNAME} --password-stdin quay.io
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

      - name: Build the image
        run: cd golang && docker build --build-arg PULUMI_VERSION=${RELEASE_VERSION} --tag quay.io/spacelift/pulumi-golang:${RELEASE_VERSION} .

      - name: Push the image to quay.io
        run: docker push quay.io/spacelift/pulumi-golang:${RELEASE_VERSION}

  python:
    needs:
      - base-alpine
    name: Build and deploy the Python image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to quay.io
        run: echo ${QUAY_PASSWORD} | docker login --username ${QUAY_USERNAME} --password-stdin quay.io
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

      - name: Build the image
        run: cd python && docker build --build-arg PULUMI_VERSION=${RELEASE_VERSION} --tag quay.io/spacelift/pulumi-python:${RELEASE_VERSION} .

      - name: Push the image to quay.io
        run: docker push quay.io/spacelift/pulumi-python:${RELEASE_VERSION}

  dotnet:
    needs:
      - base-alpine
    name: Build and deploy the Python image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to quay.io
        run: echo ${QUAY_PASSWORD} | docker login --username ${QUAY_USERNAME} --password-stdin quay.io
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

      - name: Build the image
        run: cd dotnet && docker build --build-arg PULUMI_VERSION=${RELEASE_VERSION} --tag quay.io/spacelift/pulumi-dotnet:${RELEASE_VERSION} .

      - name: Push the image to quay.io
        run: docker push quay.io/spacelift/pulumi-dotnet:${RELEASE_VERSION}
